server:
  port: 8500
  servlet:
    context-path: /

openai-service:
  api-key: <api key>
  gpt-model: gpt-3.5-turbo
  audio-model: whisper-1
  http-client:
    read-timeout: 3000
    connect-timeout: 3000
  urls:
    base-url: https://api.openai.com/v1
    chat:
      completions-url: /chat/completions
    audio:
      transcriptions-url: /audio/transcriptions

logging:
  level:
    com.github.kolomolo.service.openaiclient: TRACE

spring:
  application:
    name: ai
  jackson:
    default-property-inclusion: NON_NULL

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: 'ALWAYS'
  health:
    circuitbreakers:
      enabled: true
